---
kind: Service
apiVersion: v1
metadata:
  name: with-reg-service 
spec:
  selector:
    app: with-reg
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8080
      # Port to forward to inside the pod
      targetPort: 4000
      # Port accessible outside cluster
      nodePort: 30005
  type: LoadBalancer
 
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: with-reg-deployment 
spec:
  replicas: 10
  template:
    metadata:
      labels:
        app: with-reg
    spec:
      containers:
        - name: my-node-app-container 
          image: $ACR_DNS/with-reg-build
          ports:
            - containerPort: 4000
